WebApplication1/Controllers/AppUsersController.cs
using HZC.MyOrm;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Threading.Tasks;
using HZC.MyOrm.Commons;
using HZC.MyOrm.Expressions;
using Microsoft.AspNetCore.Authorization;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "admin")]
    public class AppUsersController : Controller
    {
        private readonly MyDb _db = new MyDb();

        public async Task<ActionResult> Index()
        {
            var expr = LinqExtensions.True<AppUser>();
            expr = expr.And(u => !u.IsDelete);

            var data = await _db.Query<AppUser>()
                .Where(expr)
                .Select<AppUserListDto>(u => new AppUserListDto
                {
                    Id = u.Id,
                    No = u.No,
                    Name = u.Name,
                    DepartmentName = u.Department.Name
                }).ToListAsync();
            return View(data);
        }

        // GET: AppUsers/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var entity = await _db.Query<AppUser>().Include(u => u.Department).Where(u => u.Id == id).FirstOrDefaultAsync();
            if (entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }

        // GET: AppUsers/Create
        public async Task<ActionResult> Create()
        {
            var entity = new AppUser();
            await InitUi();
            return View(entity);
        }

        // POST: AppUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IFormCollection collection)
        {
            var entity = new AppUser();
            await TryUpdateModelAsync(entity);

            if (ModelState.IsValid)
            {
                try
                {
                    var result = _db.InsertIfNotExists(entity, u => u.No == entity.No);
                    if (result > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    ModelState.AddModelError(string.Empty, "创建失败");
                }
                catch(Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }
            }

            await InitUi();
            return View(entity);
        }

        // GET: AppUsers/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var entity = _db.Load<AppUser>(id);
            if (entity == null)
            {
                return NotFound();
            }

            await InitUi();
            return View(entity);
        }

        // POST: AppUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, IFormCollection collection)
        {
            var entity = new AppUser();
            await TryUpdateModelAsync(entity);

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _db.UpdateIfNotExitsAsync(entity, u => u.No == entity.No && u.Id != entity.Id);
                    if (result > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "更新失败");
                    }
                }
                catch(Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                }
            }

            await InitUi();
            return View(entity);
        }

        // GET: AppUsers/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var entity = await _db.Query<AppUser>().Where(u => u.Id == id).Include(u => u.Department).FirstOrDefaultAsync();
            if (entity == null)
            {
                return NotFound();
            }
            return View(entity);
        }

        // POST: AppUsers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            var entity = new AppUser();
            await TryUpdateModelAsync(entity);
            try
            {
                var result = await _db.UpdateAsync<AppUser>(id, DbKvs.New().Add("IsDelete", true));

                if (result > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "删除失败");
                }
            }
            catch(Exception e)
            {
                ModelState.AddModelError(string.Empty, e.Message);
            }

            return View(entity);
        }

        private async Task InitUi()
        {
            var departments = await _db.Query<Department>().ToListAsync();
            ViewBag.Departments = new SelectList(departments, "Id", "Name");
        }
    }
}

WebApplication1/Controllers/ApprovalsController.cs
using AutoMapper;
using HZC.MyOrm;
using HZC.MyOrm.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    [Authorize(Roles = "admin")]
    public class ApprovalsController : BaseController
    {
        private readonly MyDb _db;

        private readonly ApprovalService _service;

        private readonly IMapper _mapper;

        public ApprovalsController(IMapper mapper)
        {
            _db = MyDb.New();
            _mapper = mapper;
            _service = new ApprovalService(_mapper);
        }

        #region 首页
        public IActionResult Index(int id, ApprovalSearchParameter search)
        {
            var pageIndex = id > 0 ? id : 1;

            var where = LinqExtensions.True<Approval>();
            if (search.Department > 0)
            {
                where = where.And(a => a.DepartmentId == search.Department);
            }

            if (!string.IsNullOrWhiteSpace(search.Creator))
            {
                where = where.And(a => a.ApplicantNo == search.Creator);
            }

            if (search.CreateAtStart.HasValue)
            {
                where = where.And(a => a.CreateAt >= search.CreateAtStart.Value);
            }

            if (search.CreateAtEnd.HasValue)
            {
                where = where.And(a => a.CreateAt <= search.CreateAtEnd.Value);
            }

            if (search.Step > 0)
            {
                where = where.And(a => a.ApproveStep == search.Step);
            }

            if (search.Result > 0)
            {
                where = where.And(a => a.ApproveResult == search.Result);
            }

            if (!string.IsNullOrWhiteSpace(search.Approver))
            {
                where = where.And(a => a.ApproverNo == search.Approver || a.ConfirmNo == search.Approver);
            }

            var query = _db.Query<Approval>().Include(a => a.Department);
            var data = query.Where(where).ToPageList(pageIndex, 20, out var recordCount);

            var result = _mapper.Map<ApprovalResult>(search);

            result.PageIndex = pageIndex;
            result.RecordCount = recordCount;
            result.PageCount = recordCount / 20 + (recordCount % 20 > 0 ? 1 : 0);
            result.Data = data;

            ViewBag.Departments = new SelectList(_db.Fetch<Department>(), "Id", "Name");
            return View(result);
        }
        #endregion
        

        #region 详情

        public IActionResult Details(int id)
        {
            var entity = _db.Load<Approval>(id);
            return View(entity);
        }
        #endregion
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Head", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @User.Identity.Name
                    }
                    else
                    {
                        @Html.Raw("首页");
                    }
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="MyApprovals" asp-action="Index">申请</a></li>
                    <li><a asp-area="" asp-controller="DepartmentApprovals" asp-action="Index">审批</a></li>
                    <li><a asp-area="" asp-controller="AuditApprovals" asp-action="Index">财务</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" airea-haspopup="true"
                           aria-explanded="false">管理员 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Departments" asp-action="Index">部门管理</a></li>
                            <li><a asp-area="" asp-controller="AppUsers" asp-action="Index">用户管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-area="" asp-controller="Approvals" asp-action="Index">审批列表</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - WebApplication1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>